import { NextRequest, NextResponse } from "next/server";
import { db, schema } from "@/lib/db";
import { eq } from "drizzle-orm";
import { runBlogWriter } from "@/lib/agents/blog-writer-agent";
import { getOrCreateUser, isAdmin, canGenerateArticles } from "@/lib/auth";
import { PLAN_LIMITS } from "@/lib/agents/orchestrator";

// POST /api/pillars/:pillarId/clusters/:clusterId/generate
// Body: { isPillar?: boolean, language?: string, tone?: string, wordCount?: number }
// If isPillar=true, generates the pillar article (uses pillar.topic).
// Otherwise, generates a cluster article.
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ pillarId: string; clusterId: string }> }
) {
  const { pillarId, clusterId } = await params;
  const body = await request.json().catch(() => ({}));
  const { isPillar, language, tone, wordCount } = body as {
    isPillar?: boolean;
    language?: string;
    tone?: string;
    wordCount?: number;
  };

  const pillar = db.select().from(schema.pillars).where(eq(schema.pillars.id, pillarId)).get();
  if (!pillar) {
    return NextResponse.json({ error: "Pillar not found" }, { status: 404 });
  }

  // Read the domain's language setting
  const domain = db.select().from(schema.domains).where(eq(schema.domains.id, pillar.domainId)).get();
  const domainLanguage = domain?.language || "English";

  let topic: string;
  let keywords: string[] = [];
  let targetWordCount = wordCount || 1500;

  if (isPillar) {
    topic = pillar.topic;
    targetWordCount = wordCount || 3000; // pillar is longer
  } else {
    const cluster = db
      .select()
      .from(schema.pillarClusters)
      .where(eq(schema.pillarClusters.id, clusterId))
      .get();
    if (!cluster || cluster.pillarId !== pillarId) {
      return NextResponse.json({ error: "Cluster not found" }, { status: 404 });
    }
    topic = cluster.clusterTopic;
    keywords = cluster.clusterKeywords ? JSON.parse(cluster.clusterKeywords) : [];
  }

  // Build pillar/cluster context so the article can link during generation
  const allClusters = db
    .select()
    .from(schema.pillarClusters)
    .where(eq(schema.pillarClusters.pillarId, pillarId))
    .all();

  const pillarContext = {
    pillarTitle: pillar.topic,
    pillarSlug: pillar.pillarArticleId
      ? db.select().from(schema.articles).where(eq(schema.articles.id, pillar.pillarArticleId)).get()?.slug || ""
      : "",
    isPillarArticle: isPillar === true,
    clusters: allClusters.map((c: { articleId: string | null; clusterTopic: string }) => {
      const art = c.articleId ? db.select().from(schema.articles).where(eq(schema.articles.id, c.articleId)).get() : null;
      return {
        topic: c.clusterTopic,
        slug: art?.slug || "",
        hasArticle: !!c.articleId,
      };
    }),
  };

  // Check if user can generate articles
  const user = await getOrCreateUser();

  if (!canGenerateArticles(user)) {
    return NextResponse.json(
      { error: "Please purchase a plan to generate articles. Visit the Pricing page to get started." },
      { status: 403 }
    );
  }

  // Check article count limit — applies to ALL users including admins on paid plans
  // Only truly unlimited for admins on the "free" plan (internal testing)
  {
    const planKey = (user.plan || "free") as keyof typeof PLAN_LIMITS;
    const planConfig = PLAN_LIMITS[planKey] || PLAN_LIMITS.free;
    const maxArticles = planConfig.articles;

    // Admins on free plan have no limit (internal use)
    const isUnlimited = isAdmin(user.email) && user.plan === "free";

    if (!isUnlimited) {
      // Count articles already generated by this user (across all their domains)
      const userDomains = db.select().from(schema.domains).where(eq(schema.domains.userId, user.id)).all();
      let articleCount = 0;
      for (const d of userDomains) {
        articleCount += db.select().from(schema.articles).where(eq(schema.articles.domainId, d.id)).all().length;
      }

      if (maxArticles === 0) {
        return NextResponse.json(
          { error: "Please purchase a plan to generate articles. Visit the Pricing page to get started." },
          { status: 403 }
        );
      }

      if (articleCount >= maxArticles) {
        const upgradeMsg = user.plan === "dollar1"
          ? "You've used all 10 articles on your $1 Plan. Upgrade to the $5 Plan to get 15 more articles."
          : "You've used all 15 articles on your $5 Plan. Please contact our support team at katapariscontact@gmail.com for assistance.";
        return NextResponse.json(
          { error: upgradeMsg },
          { status: 403 }
        );
      }
    }
  }

  // Admins always use Sonnet. Paid users get model based on plan.
  let preferredModel: "sonnet" | "opus" = "sonnet";
  if (!isAdmin(user.email)) {
    const planKey = (user.plan || "free") as keyof typeof PLAN_LIMITS;
    const planConfig = PLAN_LIMITS[planKey] || PLAN_LIMITS.free;
    preferredModel = ("model" in planConfig ? planConfig.model : "sonnet") as "sonnet" | "opus";
  }

  try {
    const output = await runBlogWriter(pillar.domainId, {
      topic,
      keywords,
      tone: (tone as "professional" | "casual" | "technical") || "professional",
      wordCount: targetWordCount,
      language: language || domainLanguage,
      pillarClusterContext: pillarContext,
      preferredModel,
    });

    // Link article back to pillar/cluster
    if (isPillar) {
      db.update(schema.pillars)
        .set({ pillarArticleId: output.articleId })
        .where(eq(schema.pillars.id, pillarId))
        .run();
    } else {
      db.update(schema.pillarClusters)
        .set({ articleId: output.articleId })
        .where(eq(schema.pillarClusters.id, clusterId))
        .run();
    }

    return NextResponse.json({
      articleId: output.articleId,
      title: output.title,
      metaTitle: output.metaTitle,
      featuredImageUrl: output.featuredImageUrl,
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Generation failed" },
      { status: 500 }
    );
  }
}
