import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Sample Generated Article — See Ranqapex's AI Output Quality",
  description: "View a real article generated by Ranqapex AI. See the structure, depth, and quality before you buy. No signup required.",
  alternates: { canonical: "/sample-article" },
};
export default function Layout({ children }: { children: React.ReactNode }) { return children; }
