import { NextResponse } from "next/server";
import { db, schema } from "@/lib/db";
import { eq, sql } from "drizzle-orm";
import { getOrCreateUser, isPlanExpired } from "@/lib/auth";
import { PLAN_LIMITS } from "@/lib/agents/orchestrator";

// GET /api/credits/balance
export async function GET() {
  const user = await getOrCreateUser();
  const plan = user.plan as keyof typeof PLAN_LIMITS;
  const limits = PLAN_LIMITS[plan];

  // Calculate used credits this month
  const firstOfMonth = new Date();
  firstOfMonth.setDate(1);
  firstOfMonth.setHours(0, 0, 0, 0);

  const usedCredits = db
    .select({ total: sql<number>`COALESCE(SUM(credits_used), 0)` })
    .from(schema.creditLedger)
    .where(eq(schema.creditLedger.userId, user.id))
    .get();

  // Count articles generated by this user
  const userDomains = db.select().from(schema.domains).where(eq(schema.domains.userId, user.id)).all();
  let articleCount = 0;
  for (const d of userDomains) {
    articleCount += db.select().from(schema.articles).where(eq(schema.articles.domainId, d.id)).all().length;
  }

  return NextResponse.json({
    plan: user.plan,
    email: user.email,
    isDemo: user.email === "demo@ranqapex.com",
    credits: {
      total: limits.credits,
      used: usedCredits?.total || 0,
      remaining: limits.credits - (usedCredits?.total || 0),
    },
    articles: {
      used: articleCount,
      limit: limits.articles,
    },
    planPurchasedAt: user.planPurchasedAt || null,
    planExpired: isPlanExpired(user.planPurchasedAt || null),
    daysRemaining: user.planPurchasedAt
      ? Math.max(0, 30 - Math.floor((Date.now() - new Date(user.planPurchasedAt).getTime()) / (1000 * 60 * 60 * 24)))
      : null,
    limits,
  });
}
