"use client";

import Link from "next/link";
import { Logo } from "@/components/logo";
import { SiteFooter } from "@/components/site-footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg)" }}>
      <nav style={{ padding: "20px 24px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <Link href="/"><Logo size={36} /></Link>
          <Link href="/" style={{ fontSize: 14, fontWeight: 600, padding: "8px 20px", borderRadius: 8, background: "var(--accent)", color: "#fff", textDecoration: "none" }}>Free Audit</Link>
        </div>
      </nav>

      <article style={{ maxWidth: 760, margin: "0 auto", padding: "32px 24px 80px" }}>
        <p style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 12 }}>
          <Link href="/" style={{ color: "var(--text-muted)", textDecoration: "none" }}>Home</Link> › <span>Terms of Service</span>
        </p>
        <h1 style={{ fontSize: 32, fontWeight: 800, color: "var(--text-primary)", margin: "0 0 8px", letterSpacing: "-0.02em" }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 32 }}>Last updated: May 4, 2026</p>

        <div style={{ fontSize: 15, lineHeight: 1.75, color: "var(--text-secondary)" }}>
          <p>
            These Terms of Service govern your use of Ranqapex (ranqapex.com).
            By accessing or using our service, you agree to these terms. If you do not agree, do not use the service.
          </p>

          <h2 style={h2}>1. The Service</h2>
          <p>
            Ranqapex provides AI-powered SEO tools — site audits, keyword discovery, content generation,
            llms.txt creation, and related features. The service is delivered via the Ranqapex web application.
          </p>

          <h2 style={h2}>2. Eligibility</h2>
          <p>You must be at least 16 years old and capable of forming a binding contract to use Ranqapex.</p>

          <h2 style={h2}>3. Account &amp; Authentication</h2>
          <p>
            You authenticate via Google Sign-In. You are responsible for any activity that occurs under your account.
            Notify us immediately at <a href="mailto:ranqapexcontact@gmail.com" style={link}>ranqapexcontact@gmail.com</a> if you suspect unauthorized access.
          </p>

          <h2 style={h2}>4. Plans &amp; Payment</h2>
          <ul>
            <li>The <strong>Free</strong> plan provides limited audits, keyword discovery, and content planning.</li>
            <li>The <strong>$1 plan</strong> is a one-time payment unlocking 10 AI articles (Sonnet) for 30 days.</li>
            <li>The <strong>$5 plan</strong> is a one-time payment unlocking 15 AI articles (Opus) for 30 days.</li>
            <li>Plans are not subscriptions and do not auto-renew. Once the 30-day window expires, you may purchase another plan.</li>
            <li>Payments are processed by Razorpay. By paying, you agree to Razorpay&apos;s terms.</li>
          </ul>

          <h2 style={h2}>5. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul>
            <li>Use Ranqapex for illegal, harmful, hateful, or fraudulent content.</li>
            <li>Reverse engineer, scrape, or attempt to access our internal systems.</li>
            <li>Abuse rate limits, attempt DoS attacks, or share access tokens.</li>
            <li>Generate content that infringes copyright, trademarks, or other rights.</li>
            <li>Use the service to compete with us by reselling AI output as your own SEO platform.</li>
          </ul>

          <h2 style={h2}>6. AI-Generated Content</h2>
          <p>
            Articles, keywords, llms.txt, and other AI outputs are generated by third-party language models (Anthropic Claude, Google Gemini).
            Output may contain factual errors. <strong>You are responsible for reviewing and editing all generated content before publishing it.</strong>
            Ranqapex makes no warranty regarding the accuracy, originality, or fitness for purpose of AI-generated output.
          </p>

          <h2 style={h2}>7. Intellectual Property</h2>
          <p>
            <strong>Your content:</strong> You retain all rights to the domains, products, and content you upload.
            You grant us a limited license to process and analyze that content solely to deliver the service.
          </p>
          <p>
            <strong>Generated content:</strong> Subject to third-party AI provider terms, you own the rights to articles and outputs we generate for you.
          </p>
          <p>
            <strong>Our content:</strong> The Ranqapex name, logo, software, and branding are our intellectual property.
          </p>

          <h2 style={h2}>8. Service Availability</h2>
          <p>
            We aim for high uptime but do not guarantee uninterrupted service. We may modify or discontinue features at any time.
            Scheduled maintenance will be communicated via email when possible.
          </p>

          <h2 style={h2}>9. Termination</h2>
          <p>
            We may suspend or terminate your account if you violate these terms.
            You may stop using the service at any time. Refunds for paid plans are governed by our <Link href="/refund-policy" style={link}>Refund Policy</Link>.
          </p>

          <h2 style={h2}>10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Ranqapex&apos;s total liability for any claim arising out of these terms is limited to
            the amount you paid us in the 30 days preceding the event giving rise to liability.
            We are not liable for indirect, incidental, or consequential damages.
          </p>

          <h2 style={h2}>11. Disclaimer of Warranties</h2>
          <p>
            The service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee SEO results,
            ranking improvements, or specific outcomes from using AI-generated content.
          </p>

          <h2 style={h2}>12. Changes to These Terms</h2>
          <p>
            We may update these Terms. The &ldquo;Last updated&rdquo; date reflects the current version.
            Continued use after changes constitutes acceptance.
          </p>

          <h2 style={h2}>13. Contact</h2>
          <p>
            Questions about these terms? Email <a href="mailto:ranqapexcontact@gmail.com" style={link}>ranqapexcontact@gmail.com</a>.
          </p>
        </div>
      </article>

      <SiteFooter />
    </div>
  );
}

const h2: React.CSSProperties = { fontSize: 20, fontWeight: 700, color: "var(--text-primary)", marginTop: 32, marginBottom: 12 };
const link: React.CSSProperties = { color: "var(--accent)", textDecoration: "none" };
