import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

// Option 5: Email the internal link report to a client/team member

export async function POST(req: NextRequest) {
  const { recipientEmail, recipientName, domainUrl, suggestions, orphanPages, stats } = await req.json();

  if (!recipientEmail) {
    return NextResponse.json({ error: "Recipient email is required" }, { status: 400 });
  }

  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = Number(process.env.SMTP_PORT) || 587;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const fromEmail = process.env.FROM_EMAIL || smtpUser;

  if (!smtpHost || !smtpUser || !smtpPass) {
    return NextResponse.json({ error: "Email is not configured on this server" }, { status: 500 });
  }

  // Build HTML email
  const suggestionsHtml = (suggestions || [])
    .map((s: { sourceTitle: string; targetTitle: string; anchorText: string; reason: string; priority: string }, i: number) => `
      <tr style="border-bottom: 1px solid #e5e7eb;">
        <td style="padding: 12px 8px; font-size: 13px; color: #374151;">${i + 1}</td>
        <td style="padding: 12px 8px; font-size: 13px; color: #374151;">${s.sourceTitle}</td>
        <td style="padding: 12px 8px; font-size: 13px; color: #7C5CFC; font-weight: 600;">${s.targetTitle}</td>
        <td style="padding: 12px 8px; font-size: 13px;">
          <code style="background: #f3f0ff; color: #7C5CFC; padding: 2px 6px; border-radius: 4px; font-size: 12px;">${s.anchorText}</code>
        </td>
        <td style="padding: 12px 8px; font-size: 12px; color: #6b7280;">${s.reason}</td>
        <td style="padding: 12px 8px;">
          <span style="background: ${s.priority === "high" ? "#fef2f2" : s.priority === "medium" ? "#fffbeb" : "#ecfdf5"}; color: ${s.priority === "high" ? "#dc2626" : s.priority === "medium" ? "#d97706" : "#16a34a"}; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: capitalize;">${s.priority}</span>
        </td>
      </tr>
    `).join("");

  const orphansHtml = (orphanPages || []).length > 0
    ? `
      <div style="margin-top: 24px; padding: 16px; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px;">
        <h3 style="font-size: 14px; font-weight: 700; color: #991b1b; margin: 0 0 8px 0;">Orphan Pages (${orphanPages.length})</h3>
        <p style="font-size: 12px; color: #b91c1c; margin: 0 0 12px 0;">These pages have zero internal links pointing to them. They may not be discovered by Google.</p>
        <ul style="margin: 0; padding: 0 0 0 16px;">
          ${(orphanPages as Array<{ title: string; url: string }>).map((p) => `<li style="font-size: 13px; color: #374151; margin-bottom: 4px;">${p.title} <span style="color: #9ca3af; font-size: 11px;">(${p.url})</span></li>`).join("")}
        </ul>
      </div>
    `
    : "";

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 32px 16px;">
      <div style="text-align: center; margin-bottom: 32px;">
        <h1 style="font-size: 24px; font-weight: 700; color: #111827; margin: 0 0 8px 0;">Internal Link Analysis Report</h1>
        <p style="font-size: 14px; color: #6b7280; margin: 0;">Generated by Ranqapex for <strong>${domainUrl || "your website"}</strong></p>
      </div>

      <div style="display: flex; gap: 12px; margin-bottom: 24px;">
        <div style="flex: 1; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center;">
          <p style="font-size: 24px; font-weight: 700; color: #7C5CFC; margin: 0;">${stats?.totalPages || 0}</p>
          <p style="font-size: 12px; color: #6b7280; margin: 4px 0 0 0;">Pages Scanned</p>
        </div>
        <div style="flex: 1; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center;">
          <p style="font-size: 24px; font-weight: 700; color: #3b82f6; margin: 0;">${stats?.totalExistingLinks || 0}</p>
          <p style="font-size: 12px; color: #6b7280; margin: 4px 0 0 0;">Existing Links</p>
        </div>
        <div style="flex: 1; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center;">
          <p style="font-size: 24px; font-weight: 700; color: ${(stats?.orphanCount || 0) > 0 ? "#ef4444" : "#22c55e"}; margin: 0;">${stats?.orphanCount || 0}</p>
          <p style="font-size: 12px; color: #6b7280; margin: 4px 0 0 0;">Orphan Pages</p>
        </div>
        <div style="flex: 1; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center;">
          <p style="font-size: 24px; font-weight: 700; color: #7C5CFC; margin: 0;">${stats?.suggestionsGenerated || 0}</p>
          <p style="font-size: 12px; color: #6b7280; margin: 4px 0 0 0;">Suggestions</p>
        </div>
      </div>

      <h2 style="font-size: 16px; font-weight: 700; color: #111827; margin: 0 0 12px 0;">Linking Suggestions</h2>
      <table style="width: 100%; border-collapse: collapse; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <thead>
          <tr style="background: #f9fafb;">
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">#</th>
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">Add link on this page</th>
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">Link to this page</th>
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">Anchor Text</th>
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">Reason</th>
            <th style="padding: 10px 8px; font-size: 11px; font-weight: 600; color: #6b7280; text-align: left;">Priority</th>
          </tr>
        </thead>
        <tbody>${suggestionsHtml}</tbody>
      </table>

      ${orphansHtml}

      <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; text-align: center;">
        <p style="font-size: 12px; color: #9ca3af;">Powered by <strong style="color: #7C5CFC;">Ranqapex</strong> · Internal Link Analysis</p>
      </div>
    </div>
  `;

  try {
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: { user: smtpUser, pass: smtpPass },
    });

    await transporter.sendMail({
      from: `"Ranqapex" <${fromEmail}>`,
      to: recipientEmail,
      subject: `Internal Link Report — ${domainUrl || "Your Website"} (${suggestions?.length || 0} suggestions)`,
      html,
    });

    return NextResponse.json({ success: true, message: `Report sent to ${recipientEmail}` });
  } catch (err) {
    return NextResponse.json({ error: `Failed to send email: ${(err as Error).message}` }, { status: 500 });
  }
}
